# These are supported funding model platforms

github: #[halvardssm]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
custom: https://www.paypal.me/halvardssm
